# Generated by Django 4.1.3 on 2022-11-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('carrera', models.CharField(max_length=30, verbose_name='CARRERA')),
                ('facultad', models.CharField(max_length=30, verbose_name='FACULTAD')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('nombre', models.CharField(max_length=25, verbose_name='NOMBRE')),
                ('apellido', models.CharField(max_length=25, verbose_name='APELLIDO')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='CORREO')),
                ('nacimiento', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('telefono', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('materia', models.CharField(max_length=30, verbose_name='MATERIA')),
                ('creditos', models.PositiveIntegerField(verbose_name='CREDITOS')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='DESCRIPCION')),
                ('jornada', models.CharField(choices=[('M', 'MAÑANA'), ('N', 'NOCHE'), ('FDS', 'FIN DE SEMANA')], max_length=3, verbose_name='JORNADA')),
            ],
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAcademica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('periodo', models.CharField(max_length=7, verbose_name='PERIODO ACADEMICO')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
            ],
        ),
    ]
